version: "3"
services: 
  app:
    container_name: digof-api-app
    build:
      context: .
      args: 
        uid: "${DOCKER_UID:-1000}"
    volumes: 
      - ./:/var/www/html
    restart: always
    ports: 
      - "${DOCKER_APP_PORT}:4000"
    # env_file: 
    #   - .env
    networks: 
      digof-api:
        aliases: 
          - app
  redis:
    container_name: digof-api-redis
    image: redis:latest
    restart: unless-stopped
    volumes: 
      - "digof-api-redis:/data"
    networks: 
      digof-api:
        aliases: 
          - redis
  mysql:
    container_name: digof-api-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes: 
      - "digof-api-mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=digof
    networks: 
      digof-api:
        aliases: 
          - mysql
    ports:
      - "${ }:3306"
  adminer:
    image: adminer
    container_name: digof-api-adminer
    restart: always
    ports:
      - "${DOCKER_ADMINER_PORT:-8080}:8080"
    networks:
      digof-api:
        aliases:
          - adminer
networks: 
  digof-api:
volumes: 
  digof-api-mysql:
  digof-api-redis: